### Qoida yaratish
POST http://localhost:3000/guides
Authorization: Bearer
Content-Type: application/json

{
  "title": "",
  "content": ""
}


### Qoidalar ro'yxatini olish
GET http://localhost:3000/guides
Authorization: Bearer


### Bitta qoidani ko'rish
GET http://localhost:3000/guides/:id
Authorization: Bearer 


### Qoidani tahrirlash
PATCH http://localhost:3000/guides/:id
Authorization: Bearer
Content-Type: application/json

{
  "title": "",
  "content": ""
}


### Qoidani o'chirish
DELETE http://localhost:3000/guides/:id
Authorization: Bearer