### POST Guide
POST http://localhost:3000/guides
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzNTE0MzQzLCJleHAiOjE2OTM2MDA3NDN9.UwyU2v7Y8DpUQn7TiNiRGdyQniefIMQ6J1BYM0dKoBE
Content-Type: application/json

{
  "title": "arrivo",
  "content": "Oltinchi qoida matni"
}


### GET Guides
GET http://localhost:3000/guides
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzNDE0NjMzLCJleHAiOjE2OTM1MDEwMzN9.GRjbA5aW93Y6VSMtzj2LQhHYeYdsSRnokzgbPPs9cZk



### GET Guide
GET http://localhost:3000/guides/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJyb2xlIjoiZW1wbG95ZWUifSwiaWF0IjoxNjkzNTEwNDc5LCJleHAiOjE2OTM1OTY4Nzl9.Pj7T5D-OXCE8m_9Byv0wLok4zKIfJN-xJM5RCDoNlR4



### EDIT Guide
PATCH http://localhost:3000/guides/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzNTY0NTkzLCJleHAiOjE2OTM2NTA5OTN9.Wjv1TrKoSZxfauXZqcnTVAK56sNpuawmVH54krc09Sg
Content-Type: application/json

{
  "content": "Yig'ishtir telefonni"
}

### DELETE Guide
DELETE http://localhost:3000/guides/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzNDE0NjMzLCJleHAiOjE2OTM1MDEwMzN9.GRjbA5aW93Y6VSMtzj2LQhHYeYdsSRnokzgbPPs9cZk
