### user_guide yaratish (Admin)
POST http://localhost:3000/user-guides
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzNzMyODI3LCJleHAiOjE2OTM4MTkyMjd9.i2_P-NfP6mz6-K4AmFz4KyxZuFdW78DnU2ZURT0kBro
Content-Type: application/json

{
  "guide_id": ,
  "user_ids": []
}


### Faqat o'zini user_guides listini ko'rish
GET http://localhost:3000/user-guides
Authorization: Bearer


### Hamma user_guides listni ko'rish (Admin)
GET http://localhost:3000/user-guides/all
Authorization: Bearer


### Bitta user_guide ni ko'rish
GET http://localhost:3000/user-guides/:id
Authorization: Bearer


### user_guide ni tahrirlash (Admin)
PATCH http://localhost:3000/user-guides/:id
Authorization: Bearer
Content-Type: application/json

{
  "guide_id": ,
  "user_id":
}


### user_guide bilan tanishganini belgilash
POST http://localhost:3000/user-guides/:id/read
Authorization: Bearer
Content-Type: application/json

{
  "completed": true
}


### user_guide ni o'chirish (Admin)
DELETE http://localhost:3000/userguide/:id
Authorization: Bearer