### Login qilish
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}


### Foydalanuvchi qo'shish (Admin)
POST http://localhost:3000/users
Authorization: Bearer
Content-Type: application/json

{
  "first_name": "",
  "last_name": "",
  "age": ,
  "role": "",
  "username": "",
  "password": ""
}


### Foydalanuvchilar ro'yxatini olish (Admin)
GET http://localhost:3000/users
Authorization: Bearer


### Mening ma'lumotlarim
GET http://localhost:3000/users/me
Authorization: Bearer


### Foydalanuvchini ko'rish (Admin)
GET http://localhost:3000/users/:id
Authorization: Bearer


### Ma'lumotlarimni tahrirlash
PATCH http://localhost:3000/users/me
Authorization: Bearer
Content-Type: application/json

{
  "first_name": "",
  "last_name": "",
  "age": ,
  "username": "",
}


### Foydalanuvchi ma'lumotlarini tahrirlash (Admin)
PATCH http://localhost:3000/users/:id
Authorization: Bearer
Content-Type: application/json

{
  "first_name": "",
  "last_name": "",
  "age": ,
  "role": "",
  "username": "",
  "password": ""
}


### Foydalanuvchini o'chirish (Admin)
DELETE http://localhost:3000/users/:id
Authorization: Bearer