### POST User
POST http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzI1ODEzLCJleHAiOjE2OTM0MTIyMTN9.QK05Fonc_hAtWJeCpObu6XhM5lCwpcszEc4fg6IxZM0 
Content-Type: application/json

{
  "first_name": "Suxrob",
  "last_name": "Yuldashev",
  "age": 20,
  "role": "admin",
  "username": "suxrob",
  "password": "1234"
}

### LOGIN User
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "aziz",
  "password": "1234"
}

### GET Users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzc4NDE5LCJleHAiOjE2OTM0NjQ4MTl9.m5bK5ISmA1PgDS1lmScOMJ2vGQySuVN0SPKaDX8Urpg

### GET Me
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzc4NDE5LCJleHAiOjE2OTM0NjQ4MTl9.m5bK5ISmA1PgDS1lmScOMJ2vGQySuVN0SPKaDX8Urpg


### GET User
GET http://localhost:3000/users/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzc4NDE5LCJleHAiOjE2OTM0NjQ4MTl9.m5bK5ISmA1PgDS1lmScOMJ2vGQySuVN0SPKaDX8Urpg


### EDIT Me
PATCH http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzc4NDE5LCJleHAiOjE2OTM0NjQ4MTl9.m5bK5ISmA1PgDS1lmScOMJ2vGQySuVN0SPKaDX8Urpg
Content-Type: application/json

{
  "id": 95
}


### EDIT User
PATCH http://localhost:3000/users/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzc4NDE5LCJleHAiOjE2OTM0NjQ4MTl9.m5bK5ISmA1PgDS1lmScOMJ2vGQySuVN0SPKaDX8Urpg 
Content-Type: application/json

{
  "role": "employee"
}


### DELETE User
DELETE http://localhost:3000/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo4LCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzc4NDE5LCJleHAiOjE2OTM0NjQ4MTl9.m5bK5ISmA1PgDS1lmScOMJ2vGQySuVN0SPKaDX8Urpg


# Admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjkzMzI1ODEzLCJleHAiOjE2OTM0MTIyMTN9.QK05Fonc_hAtWJeCpObu6XhM5lCwpcszEc4fg6IxZM0  

# Employee: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJyb2xlIjoiZW1wbG95ZWUifSwiaWF0IjoxNjkzMzg1MTgwLCJleHAiOjE2OTM0NzE1ODB9.AbOqb5MfgS93TG_EuKW4ls5NnSTzA4VwTG1pSj0-_Xc